site_name: PoliSpy
site_description: "Monitoring and analyzing political speeches"
site_author: 'firminayivodji'
copyright: "Copyright &copy; 2025"

docs_dir: dashboard/

repo_name: beethogedeon/polispy
repo_url: https://github.com/beethogedeon/polispy
edit_uri: tree/mkdocs/docs # Uncomment to define a different URI/URL for the "edit" option

nav:
  - Home !: index.md
  - Sentiment Analysis: sentiment_analysis.md
  - Topic Modeling: topic_modeling.md

# +--------------------------------------------------------------------------------------------------------+
# |                                                                                                        |
# | The "theme" section allows you to define what theme to use.                                            |
# | It is also used for theme-specific options, but also for advanced stuff such as theme-extensions, if   |
# | the theme actually supports it.                                                                        |
# |                                                                                                        |
# | Read More:                                                                                             |
# | - https://www.mkdocs.org/user-guide/configuration/#theme                                               |
# |                                                                                                        |
# +--------------------------------------------------------------------------------------------------------+
theme:
  name: 'material'
  #custom_dir: 'theme'
  favicon: 'https://www.isheero.com/wp-content/uploads/2022/07/cropped-Isheero_521x512_v2-32x32.png'
  logo: 'https://www.isheero.com/wp-content/uploads/2022/07/Isheero_521x142px-BLANC.png'

  palette:
    - scheme: default
      primary: 'pink'
      accent: indigo
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
  #language: 'en'
  
  # +------------------------------------------------------------------------------------------------------+
  # |                                                                                                      |
  # | The "direction" option is commonly used together with the "language" option.                         |
  # |                                                                                                      |
  # | It allows you to change the text direction from the default left-to-right (ltr) to right-to-left     |
  # | (rtl) which is used in certain languages.                                                            |
  # |                                                                                                      |
  # | Read More:                                                                                           |
  # | - https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#directionality            |
  # |                                                                                                      |
  # +------------------------------------------------------------------------------------------------------+
  #direction: 'ltr'
  
  # +------------------------------------------------------------------------------------------------------+
  # |                                                                                                      |
  # | The "features" option allows you to enable specific features of Material, by adding them to the      |
  # | list.                                                                                                |
  # |                                                                                                      |
  # | Features are in the format <category>.<name>. As an example, the feature to enable tabs is called    |
  # | navigation.tabs.                                                                                     |
  # |                                                                                                      |
  # | The list below contains all known features of Material.                                              |
  # |                                                                                                      |
  # | Features marked with a * are currently Insiders-only. (Last update: 11th December 2021)              |
  # | https://squidfunk.github.io/mkdocs-material/insiders/                                                |
  # |                                                                                                      |
  # | Read More:                                                                                           |
  # | - https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/                           |
  # |                                                                                                      |
  # +------------------------------------------------------------------------------------------------------+
  features:
  
  # Navigation:
  #
  #- navigation.expand      # Expand all collapsable sections.
  - navigation.instant     # Instant loading pages.
  #- navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  #- navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  #- navigation.footer
  - navigation.tracking    # Updates the url with highlighted section anchor.
  
  # Search
  #
  - search.highlight # Search will highlight the searched word(s) on the page.*
  #- search.share     # Adds an option to share a search query link.*
  #- search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  - toc.integrate          # Include the TOC sections in the left navugation.

  icon:
    logo: 'material/github'
    repo: 'material/github'
  
#extra:
#  social:
#    - icon: 'fontawesome/brands/github'
#     link: 'https://github.com/isheero-ai/learning-resources'
#    - icon: 'fontawesome/brands/linkedin'
#     link: 'https://www.linkedin.com/company/isheero/'
#    - icon: 'fontawesome/brands/youtube'
#      link: 'https://www.youtube.com/@isheero'
      
  generator: true

plugins:
  - search
  - mkdocstrings
  - git-revision-date

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.toc:
      permalink: true