name: Deploy Website
  
on:
  push:
    branches:
      - main
    paths:
      - 'graphics/**'
      - 'dashboard/'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs and Material theme
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install -r dashboard/requirements.txt

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        mkdocs gh-deploy --force
